services:
  # 1. O Coletor de Métricas (Roda as queries no Firebird)
  sql-exporter:
    image: ccsplit/sql_exporter:latest
    container_name: firebird_exporter
    volumes:
      - ./sql_exporter/sql_exporter.yml:/config/sql_exporter.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - '-config.file=/config/sql_exporter.yml'
    expose:
      - 9399
    networks:
      - wpanel
    restart: always

  # 2. O Banco de Dados de Séries Temporais (Guarda o histórico)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 9090
    networks:
      - wpanel
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    restart: always

  # 3. A Interface Visual
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 23527:3000
    networks:
      - wpanel
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Troque a senha aqui
    depends_on:
      - prometheus
    restart: always

volumes:
  prometheus_data:
  grafana_data:

networks:
  wpanel:
    external: true