services:
  # 1. O Coletor de Métricas (Roda as queries no Firebird)
  sql-exporter:
    build: ./custom_exporter
    container_name: firebird_exporter
    environment:
      - TZ=America/Sao_Paulo
      - DB_HOST=192.168.0.75
      - DB_PATH=/home/latitude/firebird/data/latitude.fdb
      - DB_USER=SYSDBA
      - DB_PASSWORD=masterkey
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 29399:9399
    networks:
      - wpanel
    restart: always

  # 2. O Banco de Dados de Séries Temporais (Guarda o histórico)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 29090:9090
    networks:
      - wpanel
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=365d'
      - '--web.cors.origin=.*'
      - '--log.level=debug'
    restart: always

  # 3. A Interface Visual
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 23527:3000
    networks:
      - wpanel
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=fsg-grafana.wpanel.ind.br
      - GF_SERVER_ROOT_URL=https://fsg-grafana.wpanel.ind.br/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    depends_on:
      - prometheus
    restart: always

volumes:
  prometheus_data:
  grafana_data:

networks:
  wpanel:
    external: true