global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Job 1: Monitora o Banco de Dados (SQL)
  - job_name: 'firebird_monitoring'
    static_configs:
      - targets: ['firebird_exporter:9399']

  # Job 2: Monitora a VM (CPU/Memória/Disco)
  - job_name: 'firebird_vm'
    static_configs:
      - targets: ['192.168.0.75:9100']

  # Job 3: Monitora a VM (CPU/Memória/Disco)
  - job_name: 'wpanel_vm'
    static_configs:
      - targets: [ '192.168.0.17:9100' ]